menu:
  首页: /
  文章归档: /archives
  #分类: /categories
  标签: /tags
  友情链接: /links
  关于: /about

excerpt_link: 阅读全文 >

google_analytics: UA-5353535-6

baidu_analytics: de86f16e85759414cb73dd76433ae1b7

rss: /atom.xml

comment_provider: duoshuo
# Duoshuo comment
duoshuo:
  short_name: dzhai
  share: true